apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv
  labels:
    type: opensearch-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<OPENSEARCH_VOLUME>"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-cluster-master-opensearch-cluster-master-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: opensearch-pv    