terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

# Configure Docker provider for authentication with registries
# Credentials can be provided via:
# 1. Environment variables: DOCKER_HOST, DOCKER_CERT_PATH, DOCKER_TLS_VERIFY
# 2. ~/.docker/config.json file (generated by 'docker login')
# 3. Terraform variables (see variables.tf)
provider "docker" {
  host = "unix:///var/run/docker.sock"
  
  # For registry authentication, ensure you've run:
  # docker login -u <username> -p <password> registry.rocketsoftware.com
  # 
  # Or set environment variables before running terraform:
  # export DOCKER_USERNAME="your_username"
  # export DOCKER_PASSWORD="your_password"
}
