apiVersion: v1
data:
  OPENAI_API_KEY: c2stc3ZjYWNjdC1yRkRhVE9PSjdBMjBNNUR0b1ZZdDVwZmdwQmJoeldCRVR0S1hsbWJvNjF3d0NMZ3BYTWhNNnU4aWJ1UHlPYmZfRG1vWFlFM09YVDNCbGJrRkpXcFNCNHB4RGMweGYyMkVnTGNDRG43TV9mdDdtX29Id1I1RXlwZnJMeUJ2TUExblFsbzR0aHJiS3czV1ZFcl84MXNVaFNhanNnQQ==
kind: Secret
metadata:
  name: metadata-extraction-secrets
type: Opaque