apiVersion: v1
kind: PersistentVolume
metadata:
  name: process-pv-storage
  labels:
    type: process-pv-storage
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<PROCESS_PV_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: process-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      type: process-pv-storage
