apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config
  namespace: <NGINX_NAMESPACE>
data:
  custom-config.conf: |
    location = /contentautomation/ {
      auth_basic "Restricted Access";
      auth_basic_user_file /etc/nginx/.htpasswd;
      client_max_body_size 100M;
      return 301 https://$host:8444/contentautomation/index.html;
    }
    location / {
      proxy_redirect http://$host/ https://$host:8444/;
    }
